### ISSUE TITLE
massive error mid install (not sure if its a bug with me or just the version)

### ISSUE THREAD

**Issue by Fazfoxy** [Kyiro/Fortnite-ManifestsArchive#12]
tried 2 different 12.50 installs and both output this error but continued going 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fazfoxy\Downloads\EasyInstaller\legendary\downloader\workers.py", line 70, in run
    r = self.session.get(job.url, timeout=self.dl_timeout)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='epicgames-download1.akamaized.net', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\logging\handlers.py", line 1431, in emit
    self.enqueue(self.prepare(record))
  File "C:\Python39\lib\logging\handlers.py", line 1393, in enqueue
    self.queue.put_nowait(record)
AttributeError: 'NoneType' object has no attribute 'put_nowait'
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python39\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Fazfoxy\Downloads\EasyInstaller\legendary\downloader\workers.py", line 73, in run
    logger.warning(f'Chunk download for {job.guid} failed: ({e!r}), retrying...')
Message: 'Chunk download for 329730012347309009777899669909903318330 failed: (ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host=\'epicgames-download1.akamaized.net\', port=443): Read timed out. (read timeout=10.0)"))), retrying...'
Arguments: ()
it did continue downloading though.

**Comment by Fazfoxy** [comment]
i've encountered this error 4 (5)(6)(7)(8)(10)times in 1 install and 1 time in the previous install which i aborted to attempt to grab a copy of the error

**Comment by nutterthanos** [comment]
I have been getting a similar error with https://github.com/polynite/splash
